<?php 
	$this->headTitle('Главная', 'PREPEND');

	$this->headMeta()	->appendName('keywords', $this->keywords)
						->appendName('description', $this->description); 
	
	?>
	

	
	<?php if(Zend_Auth::getInstance()->hasIdentity()):?>
	<?php $url = $this->url(array('controller' => 'edit-content', 'action' => 'edit-page', 'id' => 1), 'default'); ?>
	<p><a href = "<?php echo $url;?>">Редактировать</a></p>
	<?php endif;?>
	
	<?php echo $this->textpage;?>
	
	<?php echo $this->promos();?>

	
