					
					<ul>												
						<li class="b1">
                            <a href="<?php echo $this->url(array('id' => '1'), 'fullService');?>"></a>
						</li>

						<li class="b2">
							<a href="<?php echo $this->url(array('id' => '2'), 'fullService');?>"></a>
						</li>

						<li class="b3">
							<a href="<?php echo $this->url(array('id' => '3'), 'fullService');?>"></a>
						</li>

						<li class="b4">
							<a href="http://facebook.com/o.hudenko"  target="_blank"></a>
						</li>
					</ul>