
<!-- 
&copy; 
<?php if('2013' == date('Y')): ?>
	2013
<?php else: ?>
2013 - <?php echo date('Y'); ?>
<?php endif; ?> 
Dialan Telecom Service. Все права защищены.
<p>
	Телефоны: 0957788338, 0501122334 
<br />

	Почта: 
	<a href="mailto:orishko@mail.com"  target="_blank">
		orishko@mail.com
	</a>
</p>

<p>
	Powered by 
	<a href="http://facebook.com/o.hudenko"  target="_blank">
		Oleksandr Hudenko 
	</a>
	<br />
	mail: 
	<a href="mailto:gudenko@mail.com"  target="_blank">
		gudenko@mail.com
	</a>
</p>

-->
<div class="yes">
<ul>
	<a href=#><li>О КОМПАНИИ</li></a>
	<a href=#><li>ВАКАНСИИ</li></a>
</ul>
</div>
<div class="no">
<ul>
	<a href=#><li>КОНТАКТЫ</li></a>
</ul>
</div>
<div style="text-align:right;font-size:10px;">
&copy; 
<?php if('2013' == date('Y')): ?>
	2013
<?php else: ?>
2013 - <?php echo date('Y'); ?>
<?php endif; ?> 
Dialan Telecom Service. Все права защищены.Powered by 
	<a href="http://facebook.com/o.hudenko"  target="_blank">
		Oleksandr Hudenko 
	</a>
	</div>