					<?php $classes = array('m1', 'm2', 'm3', 'm4'); ?>
				
					<ul class="navigation">
						<?php foreach ($this->container as $link):?>
							<?php $class = array_shift($classes); ?>
							<li class="<?php echo $link->isActive() ? 'active ' . $class : $class; ?>">
							<?php if($link->isActive()) :?>
								<a class ='active' href="<?php echo $link->getHref();?>">
								<?php echo $link->label;?></a>
							<?php else : ?>
								<a href="<?php echo $link->getHref();?>">
								<?php echo $link->label;?></a>
							<?php endif;?>
							</li>
						<?php endforeach;?>
						<li class="m4"><a href="#dialog" name="modal">Подключиться</a></li>
						
						<!-- <li class="active m1">
                            <a class="active" href="#">Главная</a>
						</li>

						<li class="m2">
							<a href="#">О нас</a>
						</li>

						<li class="m3">
							<a href="#">Услуги</a>
						</li>

						<li class="m4">
							<a href="#">Контакты</a>
						</li> -->
						
						
					</ul>