<!--[if lt IE 9]>
 <style>
  .mail { margin-top: 100px!important; top:0px;
  }
 </style>
<![endif]-->
<div class="mail">
<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'),'default');?>>" > <img style="margin:30px 0 0 20px; border:none" src="/images/logo2.png" /></a>
<p style="font-size:24px; color:#FFFFFF; text-align:center">Благодарим за заявку</p>
<p style="font-size:18px; color:#FFFFFF; text-align:center">В ближайшее время с Вами свяжется представитель<br /> контакт-центра</p>  
<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index'),'default');?>"> <img style="margin:30px 0 0 200px; border:none" src="/images/button2.png" /></a>
</div>